
#配置区块链端口
web3j:
  client-address: http://localhost:8545


spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/gethspringboot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #springboot默认是不注入这些属性值的，需要自己绑定
        #druid数据源专有配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      #配置监控统计拦截的filters.stat:监控统计、log4j：日志记录、wall:防止sqlz注入
      #如果允许时报错 java.lang.ClassNotFoundException:org.apache.log4j.Pro
      #则导入log4j依赖即可，Maven地址：https://mvnrepository.com.artifact/
      filters: stat,wall,log4j
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis


